package cn.tklvyou.guiderobot.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.tklvyou.guiderobot.model.NavLocation;

import cn.tklvyou.guiderobot.model.NavLocationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig navLocationDaoConfig;

    private final NavLocationDao navLocationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        navLocationDaoConfig = daoConfigMap.get(NavLocationDao.class).clone();
        navLocationDaoConfig.initIdentityScope(type);

        navLocationDao = new NavLocationDao(navLocationDaoConfig, this);

        registerDao(NavLocation.class, navLocationDao);
    }
    
    public void clear() {
        navLocationDaoConfig.clearIdentityScope();
    }

    public NavLocationDao getNavLocationDao() {
        return navLocationDao;
    }

}
